name: Change Request
description: Request a change to inform the community on what existing part of the project can be improved!
title: "[Change Request]: "
labels: ["change request",]
assignees:
  - Bidon15
body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding new ways of improving existing features!
  - type: input
    id: summary
    attributes: 
      label: Summary
      description: Keep it simple and short. This helps with further deep dive into the change request
      value: "Example: New ABC plug-n-play replacement for lib XYZ that is used in DEF part"
    validations:
      required: true
  - type: textarea
    id: gain
    attributes:
      label: Gain 
      description: What is the gain of this change request? Please describe the benefits
      value: "Example: After official release of ABC lib, it has proven in many benchmarks to outperform existing XYZ lib by N%"
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: What are the resources that you have read to present it to others?
      value: "Example: https:/some links"
    validations:
      required: true
  - type: textarea
    id: ideas
    attributes:
      label: Implementation ideas
      description: What ideas do you have on how to implement this?
      value: | 
        Example: We can start with wrapping existing N code snippet to make implementation easier for feature ABC. 
        Still the other option is re-writing this code snippet to achieve neater code design.
  - type: textarea
    id: urgency
    attributes:
      label: Urgency
      description: How urgent this request is? 
      options:
        - Don't Know
        - Low
        - Medium
        - High
        - Critical
      validations:
        required: true
