name: General Question
description: Ask a question here regarding the existing features on the project! (StackOverflow like questions)
title: "[General Question]: "
labels: ["question",]
assignees:
  - Bidon15
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping building up the knowledge base for others!
  - type: textarea
    id: question 
    attributes: 
      label: Question
      description: | 
        Be creative and describe your question as as detailed as possible for others to get into the context
    validations:
      required: true
