# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Label issues
on:
  issues:
    types: [opened]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: mheap/github-action-required-labels@v2
        with:
          add-labels: "needs:triage"
          ignore-if-labeled: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
