name: Go Test

on:
  push:
    branches: 
      - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'

    - name: test
      run: go test -v ./...
